server:
  port: 1988

spring:
  application:
    name: springboot
mybatis:
  mapper-locations: classpath:sql-mapper/*.xml

# 主从库配置
master:
    url: jdbc:mysql://rm-bp17330s3si44dsz7bo.mysql.rds.aliyuncs.com:3306/dbs_0
#    url: jdbc:mysql://localhost:8066/TESTDB
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Ygy250725
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    type: com.alibaba.druid.pool.DruidDataSource
slave:
    url: jdbc:mysql://rm-bp17330s3si44dsz7bo.mysql.rds.aliyuncs.com:3306/dbs_1

