server:
  port: 1988
  contextPath:  /sharding

spring:
  application:
    name: springboot
  profiles:
    active: home
mybatis:
  mapper-locations: classpath:sql-mapper/*.xml

#jwt parameters
jwt:
  header: Authorization
  secret: derrick.yang
  expiration: 604800
  tokenHead: "Bearer "

security:
  basic:
    enabled: false
